version: "3.9"
services:
  mssql:
    container_name: db_sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
  
  elasticsearch:
    container_name: elasticsearch_8.4.1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/datafile
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - "http.publish_host=_local_"
    networks:
      - elasticsearchnetwork

  kibana:
    container_name: kibana_8.4.1
    image: docker.elastic.co/kibana/kibana:8.4.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticsearchnetwork
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   
       
networks:
  default:
    
  elasticsearchnetwork:
    driver: bridge

volumes:
  elastic-data: